# Generated by Django 5.0.2 on 2024-08-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MaudeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_type',
            field=models.CharField(choices=[('cafeInMaude', 'CafeInMaude'), ('CITP', 'CITP')], default='CITP', max_length=20),
        ),
    ]
