fmod LIST-REV { X :: TRIV } is
  var  E : X$Elt .
  var  L : List .
  vars P S : NeList .

  sorts NeList List .
  subsort X$Elt < NeList < List .

  op nil : -> List [ctor] .
  op __ : List List -> List [ctor assoc id: nil prec 25] .
  op __ : NeList List -> NeList [ctor ditto] .
  op __ : List NeList -> NeList [ctor ditto] .

  op rev : List -> List .
  eq rev(nil) = nil .
  eq rev(E) = E .
  eq rev(P S) = rev(S) rev(P) .

endfm

fmod NAT-LIST-REV is
  protecting LIST-REV { Nat } .
endfm
